version: "2"
services:
  web:
    image: node:carbon
    tty: true
    working_dir: /app
    command: node index.js --colors
    volumes:
      - "${PWD}:/app:delegated"
    ports:
      - "8000:8000"
      - "8080:8080"
    links:
      - nginx:nginx-proxy

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"